//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChallengeSevenSegment.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChallengeSevenSegment.Resources.LocalResource", typeof(LocalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No fue posible decodificar el número..
        /// </summary>
        internal static string Error_Decoding_Number {
            get {
                return ResourceManager.GetString("Error_Decoding_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El archivo no contiene tres (3) files o está vacío..
        /// </summary>
        internal static string Error_Empy_File {
            get {
                return ResourceManager.GetString("Error_Empy_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El archivo no existe. Por favor verifique e intente nuevamente..
        /// </summary>
        internal static string Error_File_No_Exist {
            get {
                return ResourceManager.GetString("Error_File_No_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decifrando bloque número {0}: El tamaño de la fila y columna tiene que ser de tres (3)..
        /// </summary>
        internal static string Error_InconsistentRow {
            get {
                return ResourceManager.GetString("Error_InconsistentRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error decifrando bloque número {0}: Solo se permiten los valores: &apos;.&apos; , &apos;_&apos; y &apos;|&apos;..
        /// </summary>
        internal static string Error_IncorrectCharacters {
            get {
                return ResourceManager.GetString("Error_IncorrectCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Todas las filas y columnas deben de contener la misma longitud (3x3) respectivamente..
        /// </summary>
        internal static string Error_NumberLength {
            get {
                return ResourceManager.GetString("Error_NumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: El tamaño de la secuencia de números no es correcta. Recuerde que cada número está representado por tres (3) filas y tres  (3) columnas..
        /// </summary>
        internal static string Error_NumberSecuenceNotValid {
            get {
                return ResourceManager.GetString("Error_NumberSecuenceNotValid", resourceCulture);
            }
        }
    }
}
